### ISSUE TITLE
开 gh 和 vercel 镜像网址

### ISSUE THREAD

**Issue by oflg** [Zacharia2/TWPUB-BOOK#2]
打算开个 gh-pages 吗？甚至 vercel.com 的高速镜像网站。
可以给 twpub 库和汉化过的 TiddlyStow 用。

**Comment by Zacharia2** [comment]
嗯嗯，可是有相关的文档嘛，我对此一无所知。

**Comment by Zacharia2** [comment]
> 打算开个 gh-pages 吗？甚至 vercel.com 的高速镜像网站。 可以给 twpub 库和汉化过的 TiddlyStow 用。

嗯嗯，可是有相关的文档嘛，我对此一无所知。

**Comment by oflg** [comment]
vercel：https://zhuanlan.zhihu.com/p/156722761
