### ISSUE TITLE
申请权限

### ISSUE THREAD

**Issue by zhangaz1** [Zacharia2/TWPUB-BOOK#6]
用户名：zhangaz1
mail：[zhangaz1@qq.com](mailto:zhangaz1@qq.com)

**Comment by Zacharia2** [comment]
OK

**Comment by Zacharia2** [comment]
ok\(^o^)/~


是一只软软呀
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Zacharia2/TWPUB-Library"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月15日(星期一) 上午9:19
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Zacharia2/TWPUB-Library] 申请权限 (Issue #6)





 
用户名：zhangaz1
 ***@***.***
